// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.service.impl;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SellerServiceImpl_Roo_Service {
    
    declare @type: SellerServiceImpl: @Service;
    
    declare @type: SellerServiceImpl: @Transactional;
    
}
