// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;

import cz.kolomet.domain.codelist.CategoryType;
import java.io.Serializable;

privileged aspect CategoryType_Roo_Serializable {
    
    declare parents: CategoryType implements Serializable;
    
    private static final long CategoryType.serialVersionUID = 1L;
    
}
