// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;

import cz.kolomet.domain.codelist.Codelist;
import java.io.Serializable;

privileged aspect Codelist_Roo_Serializable {
    
    declare parents: Codelist implements Serializable;
    
    private static final long Codelist.serialVersionUID = 1L;
    
}
