// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;

import cz.kolomet.domain.codelist.FigureHeight;
import java.io.Serializable;

privileged aspect FigureHeight_Roo_Serializable {
    
    declare parents: FigureHeight implements Serializable;
    
    private static final long FigureHeight.serialVersionUID = 1L;
    
}
