// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;

import cz.kolomet.domain.codelist.PlaceType;
import java.io.Serializable;

privileged aspect PlaceType_Roo_Serializable {
    
    declare parents: PlaceType implements Serializable;
    
    private static final long PlaceType.serialVersionUID = 1L;
    
}
