// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;

import java.io.Serializable;

privileged aspect ProductAttributeType_Roo_Serializable {
    
    declare parents: ProductAttributeType implements Serializable;
    
    private static final long ProductAttributeType.serialVersionUID = 1L;
    
}
