// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;

import cz.kolomet.domain.codelist.Region;
import java.io.Serializable;

privileged aspect Region_Roo_Serializable {
    
    declare parents: Region implements Serializable;
    
    private static final long Region.serialVersionUID = 1L;
    
}
