// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain.codelist;


privileged aspect SellerStatus_Roo_JavaBean {
    
    public Integer SellerStatus.getPriority() {
        return this.priority;
    }
    
    public void SellerStatus.setPriority(Integer priority) {
        this.priority = priority;
    }
    
}
