// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplicationRoleIntegrationTest_Roo_Configurable {
    
    declare @type: ApplicationRoleIntegrationTest: @Configurable;
    
}
