// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.ApplicationPermission;
import java.io.Serializable;

privileged aspect ApplicationPermission_Roo_Serializable {
    
    declare parents: ApplicationPermission implements Serializable;
    
    private static final long ApplicationPermission.serialVersionUID = 1L;
    
}
