// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.ApplicationUser;
import java.io.Serializable;

privileged aspect ApplicationUser_Roo_Serializable {
    
    declare parents: ApplicationUser implements Serializable;
    
    private static final long ApplicationUser.serialVersionUID = 1L;
    
}
