// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.ApplicationRole;

privileged aspect ApplicationRole_Roo_JavaBean {
    
    public String ApplicationRole.getRoleName() {
        return this.roleName;
    }
    
    public void ApplicationRole.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
