// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.Category;
import java.io.Serializable;

privileged aspect Category_Roo_Serializable {
    
    declare parents: Category implements Serializable;
    
    private static final long Category.serialVersionUID = 1L;
    
}
