// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.DomainEntity;
import java.io.Serializable;

privileged aspect DomainEntity_Roo_Serializable {
    
    declare parents: DomainEntity implements Serializable;
    
    private static final long DomainEntity.serialVersionUID = 1L;
    
}
