// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.PlaceComment;
import java.io.Serializable;

privileged aspect PlaceComment_Roo_Serializable {
    
    declare parents: PlaceComment implements Serializable;
    
    private static final long PlaceComment.serialVersionUID = 1L;
    
}
