// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import java.io.Serializable;

privileged aspect PlacePhotoUrl_Roo_Serializable {
    
    declare parents: PlacePhotoUrl implements Serializable;
    
    private static final long PlacePhotoUrl.serialVersionUID = 1L;
    
}
