// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import java.io.Serializable;

privileged aspect ProductComment_Roo_Serializable {
    
    declare parents: ProductComment implements Serializable;
    
    private static final long ProductComment.serialVersionUID = 1L;
    
}
