// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.ProductAttribute;
import java.io.Serializable;

privileged aspect ProductAttribute_Roo_Serializable {
    
    declare parents: ProductAttribute implements Serializable;
    
    private static final long ProductAttribute.serialVersionUID = 1L;
    
}
