// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.RegistrationRequest;
import java.io.Serializable;

privileged aspect RegistrationRequest_Roo_Serializable {
    
    declare parents: RegistrationRequest implements Serializable;
    
    private static final long RegistrationRequest.serialVersionUID = 1L;
    
}
