// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.Seller;
import javax.persistence.Entity;

privileged aspect Seller_Roo_Jpa_Entity {
    
    declare @type: Seller: @Entity;
    
}
