// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.kolomet.domain;

import cz.kolomet.domain.Seller;
import java.io.Serializable;

privileged aspect Seller_Roo_Serializable {
    
    declare parents: Seller implements Serializable;
    
    private static final long Seller.serialVersionUID = 1L;
    
}
